name: Get Clips from Twitch
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: https://troll-selecta.elsmore.me/.netlify/functions/get-clipsbackground