name: Get Clips from Twitch
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: https://troll-selecta.elsmore.me/.netlify/functions/push-clips-to-twitchbackground

curl -H "Accept: application/vnd.github.everest-preview+json"
\ -H "Authorization: token <your-token-here>"
\ --request POST
\ --data '{"event_type": "do-something", "client_payload": { "text": "a title"}}'
\ https://api.github.com/repos/ukmadlz/channel-point-app/dispatches